[package]
name = "shelter"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.12.1"
base64 = "0.22.1"
clap = { version = "4.5.53", features = ["derive"] }
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.28"
