[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
base64.workspace = true
clap.workspace = true
hex.workspace = true
hickory-resolver.workspace = true
log.workspace = true
reqwest = { version = "0.12.15", features = ["blocking"] }
tokio.workspace = true
urandom = "0.2.2"
